# Generated by Django 4.2.1 on 2023-05-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('complited', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 5, 21, 12, 57, 53, 625077, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
