# Generated by Django 4.2.1 on 2023-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('', ''), ('Django', 'Django'), ('React', 'React')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
