# Generated by Django 4.2.1 on 2023-06-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='todo.task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('', ''), ('Django', 'Django'), ('React', 'React')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='todoplan',
            name='todo',
            field=models.ManyToManyField(blank=True, null=True, to='todo.todo'),
        ),
        migrations.DeleteModel(
            name='Todo_New',
        ),
    ]
