# Generated by Django 4.2.1 on 2023-05-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complite',
            new_name='complited',
        ),
    ]
