# Generated by Django 4.2.1 on 2023-05-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_complite_todo_complited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complited',
            new_name='completed',
        ),
    ]
