# Generated by Django 4.2.1 on 2023-06-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_tasks_alter_todo_category_alter_todoplan_todo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('Django', 'Django'), ('React', 'React')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
