# Generated by Django 4.2.1 on 2023-05-29 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_new_todoplan_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('complited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='todo_new',
            name='category',
            field=models.CharField(choices=[('', ''), ('Django', 'Django'), ('React', 'React')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='todo_new',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_new',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo_new',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo_new',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='todo_new',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='todo.task_new'),
        ),
    ]
