# Generated by Django 4.2.1 on 2023-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowApiUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access', models.CharField(choices=[('Admin', 'Admin'), ('Authenticated user', 'Authenticated user'), ('Any', 'Any')], default='Admin', max_length=20)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('url_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('api_category', models.ManyToManyField(to='home.showapiurl')),
            ],
        ),
    ]
