# Generated by Django 4.2.1 on 2023-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_showapiurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='showapiurl',
            name='api_category',
            field=models.ManyToManyField(to='home.categoryapi'),
        ),
    ]
