# Generated by Django 4.2.1 on 2023-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_categoryapi_showapiurl_api_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showapiurl',
            name='api_category',
        ),
        migrations.AddField(
            model_name='categoryapi',
            name='api_category',
            field=models.ManyToManyField(to='home.showapiurl'),
        ),
    ]
